services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: nextjs-chatbot-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: nextjs-chatbot-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d chatbot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nextjs-chatbot-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: nextjs-chatbot-postgres-data
  redis_data:
    name: nextjs-chatbot-redis-data
